capital_cities = { 
"Albania" : "Tirana",
"Andorra" : "Andorra la Vella",
"Armenia" :	"Yerevan",
"Austria" : "Vienna",
"Azerbaijan" : "Baku",
"Belarus" : "Minsk",
"Belgium" : "Brussels",
"Bosnia and Herzegovina" : "Sarajevo",
"Bulgaria" : "Sofia",
"Croatia" : "Zagreb",
"Cyprus" : "Nicossia",
"Czechia" : "Prague",
"Denmark" : "Copenhagen",
"Estonia" : "Tallinn",
"Finland" : "Helsinki",
"France" : "Paris",
"Georgia" : "Tbilisi",
"Germany" : "Berlin",
"Greece" : "Athens",
"Hungary" : "Budapest",
"Iceland" : "Rejkjavik",
"Ireland" : "Dublin",
"Italy" : "Rome",
"Kazakhstan" : "Nur-Sultan",
"Latvia" : "Riga",
"Lichtenstein" : "Vaduz",
"Lithuania" : "Vilnius",
"Luxembourg" : "Luxembourg",
"Malta" : "Valleta",
"Moldova" : "Chisinau",
"Monaco" : "Monaco",
"Montenegro" : "Podgorica",
"Netherlands" : "Amsterdam",
"North Macedonia" : "Skopje",
"Norway" : "Oslo",
"Poland" : "Warsaw",
"Portugal" : "Lisbon",
"Romania" : "Bucharest",
"Russia" : "Moscow",
"San Marino" :"San Marino" ,
"Serbia" : "Belgrade" ,
"Slovakia" : "Bratislava",
"Slovenia" : "Ljubljana",
"Spain"	: "Madrid",
"Sweden" : "Stockholm",
"Switzerland" : "Bern",
"Turkey" : "Ankara",
"Ukraine" : "Kyiv",
"United Kingdom" : "London",
"Vatican City" : "Vatican City"
}

#ilektra min deis auto